---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    tag: 6.3.3
  # Currently the Zarf Agent can only mutate urls that are proper URIs (i.e. scheme://host/repo)
  url: https://github.com/stefanprodan/podinfo.git
