apiVersion: v1
kind: Service
metadata:
  name: jackal-connect-longhorn-ui
  labels:
    # Enables "jackal connect longhorn-ui"
    jackal.dev/connect-name: longhorn-ui
  annotations:
    jackal.dev/connect-description: "Connect to the Longhorn User Interface"
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: longhorn-ui
