apiVersion: v1
kind: Service
metadata:
  name: jackal-connect-registry
  labels:
    # Enables "jackal connect registry"
    jackal.dev/connect-name: registry
  annotations:
    jackal.dev/connect-description: "Internal Jackal Registry (run jackal tools registry login to authenticate)"
    jackal.dev/connect-url: "/v2/_catalog"
spec:
  ports:
  - port: 5000
