[build]
  base = "site/"
  command = "npm run build"
  publish = "dist/"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . src/content/docs ../examples/"

[build.environment]
  NODE_VERSION = "20.11.1"
