apiVersion: v1
kind: Secret
metadata:
    name: private-registry
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: |-
        {
          "auths": {
            "registry1.dso.mil": {
              "username": "###ZARF_VAR_REGISTRY1_USERNAME###",
              "password": "###ZARF_VAR_REGISTRY1_CLI_SECRET###",
              "email": "",
              "auth": "###ZARF_VAR_REGISTRY1_AUTH###"
            }
          }
        }
