name: save-logs
description: "Save debug logs"

inputs:
  suffix:
    description: 'Suffix to append to the debug log'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Fix log permissions
      run: |
        sudo chown $USER /tmp/zarf-*.log || echo ""
      shell: bash

    - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: debug-log${{ inputs.suffix }}
        path: /tmp/zarf-*.log
