persistence:
  enabled: ###JACKAL_VAR_REGISTRY_PVC_ENABLED###
  storageClass: "###JACKAL_STORAGE_CLASS###"
  size: "###JACKAL_VAR_REGISTRY_PVC_SIZE###"
  existingClaim: "###JACKAL_VAR_REGISTRY_EXISTING_PVC###"
  accessMode: "###JACKAL_VAR_REGISTRY_PVC_ACCESS_MODE###"

image:
  repository: "###JACKAL_REGISTRY###/###JACKAL_CONST_REGISTRY_IMAGE###"
  tag: "###JACKAL_CONST_REGISTRY_IMAGE_TAG###"

imagePullSecrets:
  - name: private-registry

secrets:
  htpasswd: "###JACKAL_HTPASSWD###"
  configData:
    http:
      secret: "###JACKAL_REGISTRY_SECRET###"

service:
  nodePort: "###JACKAL_NODEPORT###"

resources:
  requests:
    cpu: "###JACKAL_VAR_REGISTRY_CPU_REQ###"
    memory: "###JACKAL_VAR_REGISTRY_MEM_REQ###"
  limits:
    cpu: "###JACKAL_VAR_REGISTRY_CPU_LIMIT###"
    memory: "###JACKAL_VAR_REGISTRY_MEM_LIMIT###"

fullnameOverride: "jackal-docker-registry"

podLabels:
  jackal.dev/agent: "ignore"

autoscaling:
  enabled: ###JACKAL_VAR_REGISTRY_HPA_ENABLE###
  minReplicas: "###JACKAL_VAR_REGISTRY_HPA_MIN###"
  maxReplicas: "###JACKAL_VAR_REGISTRY_HPA_MAX###"
  targetCPUUtilizationPercentage: 80

caBundle: |
  ###JACKAL_VAR_REGISTRY_CA_BUNDLE###

extraEnvVars:
  ###JACKAL_VAR_REGISTRY_EXTRA_ENVS###
