mounts:
  - source: "../docs/1-getting-started"
    target: "../docsNew"
    ignores: [".templates"]

  # - source: "../examples"
  #   target: "../examples"

  # - source: "../packages"
  #   target: "../packages"

  # - source: "../CONTRIBUTING.md"
  #   target: "../docs/contributing"
