mounts:
  - source: "../docs"
    docsRoot: "0-zarf-overview.md"
    rootTitle: "Documentation"
    target: "../docs-hugo"
    ignores: [".templates"]

  # - source: "../examples"
  #   target: "../docsNew/examples"

  # - source: "../examples"
  #   target: "./content/docs"

  # - source: "../CONTRIBUTING.md"
  #   target: "../docs/contributing"
