mounts:
  - source: "../docs"
    target: "./content"
    ignores: [".templates"]

  - source: "../examples"
    target: "./content/docs"

  # - source: "../CONTRIBUTING.md"
  #   target: "../docs/contributing"
