mounts:
  - source: '../docs'
    target: 'content/en/docs'
    ignores: ['.templates']

  - source: '../adr'
    target: 'content/en/docs/adr'

  - source: '../examples'
    target: 'content/en/docs/examples'

  - source: '../packages'
    target: 'content/en/docs/packages'

  - source: '../CONTRIBUTING.md'
    target: 'content/en/docs/contributing'
