apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: oci
  interval: 30s
  # TODO: (@WSTARR) - Make this automatic
  insecure: true
  url: oci://ghcr.io/stefanprodan/charts
