apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: zarf
webhooks:
  - name: agent-pod.zarf.dev
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values:
            # Ensure we don't mess with kube-system
            - "kube-system"
        # Allow ignoring whole namespaces
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    objectSelector:
      matchExpressions:
        # Always ignore specific resources if requested by annotation/label
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
        # Ignore K3s Klipper
        - key: svccontroller.k3s.cattle.io/svcname
          operator: DoesNotExist
    clientConfig:
      service:
        name: agent-hook
        namespace: zarf
        path: "/mutate/pod"
      caBundle: "###ZARF_AGENT_CA###"
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    sideEffects: None
  - name: agent-flux-gitrepo.zarf.dev
    namespaceSelector:
      matchExpressions:
        # Ensure we don't mess with kube-system
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values:
            - "kube-system"
        # Allow ignoring whole namespaces
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    objectSelector:
      matchExpressions:
        # Always ignore specific resources if requested by annotation/label
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    clientConfig:
      service:
        name: agent-hook
        namespace: zarf
        path: "/mutate/flux-gitrepository"
      caBundle: "###ZARF_AGENT_CA###"
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - "source.toolkit.fluxcd.io"
        apiVersions:
          - "v1beta1"
          - "v1beta2"
        resources:
          - "gitrepositories"
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    sideEffects: None
  - name: agent-fleet-gitrepo.zarf.dev
    namespaceSelector:
      matchExpressions:
        # Ensure we don't mess with kube-system
        - key: "kubernetes.io/metadata.name"
          operator: NotIn
          values:
            - "kube-system"
        # Allow ignoring whole namespaces
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    objectSelector:
      matchExpressions:
        # Always ignore specific resources if requested by annotation/label
        - key: zarf.dev/agent
          operator: NotIn
          values:
            - "skip"
            - "ignore"
    clientConfig:
      service:
        name: agent-hook
        namespace: zarf
        path: "/mutate/fleet-gitrepo"
      caBundle: "###ZARF_AGENT_CA###"
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - "fleet.cattle.io"
        apiVersions:
          - "v1alpha1"
        resources:
          - "gitrepos"
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    sideEffects: None
