apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitea
  namespace: jackal
spec:
  gateways:
    - istio-system/public
  hosts:
    - gitea.###JACKAL_VAR_DOMAIN###
  http:
    - route:
        - destination:
            host: jackal-gitea-http.jackal.svc.cluster.local
            port:
              number: 3000
