apiVersion: v1
kind: Service
metadata:
  name: kiwix
  annotations:
    zarf.dev/connect-description: "View the Kiwix web interface"
  labels:
    zarf.dev/connect-name: kiwix
spec:
  selector:
    app: kiwix-serve
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
