---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-oci
  namespace: flux-system
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: podinfo
  targetNamespace: podinfo-oci
