---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  # TODO: (@WSTARR) - Make this automatic
  insecure: true
  url: oci://ghcr.io/stefanprodan/manifests/podinfo
  ref:
    tag: 6.4.0
