# eksctl create cluster --config-file=eks.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ###JACKAL_VAR_EKS_CLUSTER_NAME###
  region: ###JACKAL_VAR_EKS_CLUSTER_REGION###
  version: "###JACKAL_VAR_EKS_CLUSTER_VERSION###"

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: "###JACKAL_VAR_EBS_DRIVER_VERSION###"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
- instanceType: ###JACKAL_VAR_EKS_INSTANCE_TYPE###
  name: ###JACKAL_VAR_EKS_CLUSTER_NAME###-ng
  minSize: 3
  maxSize: 6
  spot: true
