apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-configmap
  namespace: jackal
  labels:
    app: jackal
data:
  templateme.properties: |
    scorpion=###JACKAL_VAR_SCORPION###
    camel_spider=###JACKAL_VAR_CAMEL_SPIDER###
    cow=moo
  tls-key: |-
    ###JACKAL_VAR_TLS_KEY###
