apiVersion: v1
kind: Namespace
metadata:
  name: pepr-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
subjects:
  - kind: ServiceAccount
    name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
  namespace: pepr-system
type: Opaque
data:
  value: >-
    MzE3MDM1YjQ2YjkzNjU4MzQ0Y2M1NjA5MzEwOWUxMDRmMzJlYzAzYzQ0MmQ4NjRlYzgyMjk3ZjZhMDFlOWQxMg==
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
  namespace: pepr-system
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDd3pDQ0FhdWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEl6TURreU1ERTNOVE16DQpPRm9YRFRJME1Ea3lNREUzTlRNek9Gb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQU5iZjVlQkJTaWoyK2RXZFdxZlNUMG91dkhrQUY2TmhTRmhPdTJJbC9sVDN3aG4vSXBWVXlFall2dGV2DQprRnZGTkRaemRCYmNpU3NxTGdOcDBRaGZsU2xSdENmL1BJekVlUXZUOExKZGRobXhvME1CdWdKWnZuSTFlSzVYDQovR3pVSG8xaGRKTGdjMDI1MCttOTBiSGluVzdENEFqSEQ2Ny8zcTIxd3FySHRYTGxjZzE3LzE2ZEFMMXQ4dUpJDQp3SlQwQUtPTFZaYnBKeTFsZEc5Q1JGNWhOcWpTUyt0MFNOTFV2WHk0ZTA4Y1lhQ2k1dDB3S3ErZTNQaVJ3RUJQDQo5WTF6TTJwNkpjNzlTb0U0WkdPZzJDNHVUaVdsTGIwL2FlYnNvZHIwOG1zR243ckRzeXJhMlQwN29NQ3Ira1JvDQp5UmwwQzhONVpHVEdIbzZSTGp3UnlLTXhvbDhDQXdFQUFhTklNRVl3UkFZRFZSMFJCRDB3TzRJNWNHVndjaTFqDQpZalUyT1RObFppMWtNVE5qTFRWbVpURXRZalZoWkMxak9EY3dabVE1TVRGaU0ySXVjR1Z3Y2kxemVYTjBaVzB1DQpjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBWjB5K1ZHRmpWeklyNkpLWVdnMk8xdzJMQUh6bFdkLytiDQpaMThPaG4wQ3VhNS8ycTU0MXIvZmEwTHk4YzNSWkk1YTJzRnNrQy9ZdWlkVHVBSDE2Y0g0KytRS2t4WXlmN1JxDQo1OWhuZDlYUVcwOWlzamtJc2hyZmVlNERFOU9XeDBObnRra2JPL1dqWWthSDN0Q2VwMWFuVmd2WHd5N093SCtWDQo0QU5mVUV3cmZxdml5ejJtS3RBYWhDVzE1S3FxcTZKeGFyM1N5bVBQeFJPSXZvRHk5bjlLV0pxVzVBT0VUMTRZDQpjTDVxSHpCUTZXVU1RVnhwU3V6WG8zYVhjaGR1YThQcG5YZVNuSmsvS2hLanYzbFlkSGF6ajJxa3lFSnUxcjZsDQpoeUtYNVNNN0o4VXlacDcvUjdVQndmdHN3RHBDV1hjMk0wNzFRcHFqYWY1TnN6OW00TlhiDQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQTF0L2w0RUZLS1BiNTFaMWFwOUpQU2k2OGVRQVhvMkZJV0U2N1lpWCtWUGZDR2Y4aQ0KbFZUSVNOaSsxNitRVzhVME5uTjBGdHlKS3lvdUEyblJDRitWS1ZHMEovODhqTVI1QzlQd3NsMTJHYkdqUXdHNg0KQWxtK2NqVjRybGY4Yk5RZWpXRjBrdUJ6VGJuVDZiM1JzZUtkYnNQZ0NNY1Bydi9lcmJYQ3FzZTFjdVZ5RFh2Lw0KWHAwQXZXM3k0a2pBbFBRQW80dFZsdWtuTFdWMGIwSkVYbUUycU5KTDYzUkkwdFM5ZkxoN1R4eGhvS0xtM1RBcQ0KcjU3YytKSEFRRS8xalhNemFub2x6djFLZ1Roa1k2RFlMaTVPSmFVdHZUOXA1dXloMnZUeWF3YWZ1c096S3RyWg0KUFR1Z3dLdjZSR2pKR1hRTHczbGtaTVllanBFdVBCSElvekdpWHdJREFRQUJBb0lCQUQvRDdPdHFaTEFZYnRhcQ0KSGlPTVlWUlIzME9ITi95WG00ajlRRlZsa2Y2MEVhbDJVZFIvOXZuTFBJTTBTZ0k1MlA5SnJzczBBZzdKc3lMMw0KTFgydkk4eEJ2MVZaUktZL2plNXBKRlpDTHhCNzYwZXd4UHI2bCs0N21RY2YvRHh0akcySFhMbFRtMVFYRCtDZg0KSUpJSi9vOUcySDZ5V0NDbU5QWlc2S0NXcUcyaVJzempJTll5ZW5lU2c4MnU1b1ZLMTF6NHhMbDhjcDlHRHJhWA0KdjRBa2dFVERtaDZsdVpmWlhCQ1hSM0ttTlNMZ0cxQUp1bTc5K1NpRTNMd1dHK3FNNnFjTFd2aDFuS2wrTVlHZg0KOGNkODdqWjNEZHh6SGVoU0lYMGFDNnQ0VEhDMXRSbmVVVk04YWNNUzRsc0NiT0JxN2NsUTZaTmVtNkNFTFp3WQ0KN1RhcFdqMENnWUVBMTN0amJrSmZVU0Ivdlo2aWVkUFM0dk9DVTNYZUtodlloZGd4MzVDVTRvTjgyRkhRUEwrUg0KbnRiVjlPQk8ranJ6ZkcxN3hHbnloeFlBT1cvMjV4bDliV21uQTRXM2dTZDZKWlJ2K3p2U2ZsNXN0aWpNNGZzLw0KZ0RVQkdzU0RpWnd5MThZd3NxWG80SlZ6anh1MmtlQVZwL0t1OE4zYlBwVVlnNjZIcHEwVGx6c0NnWUVBLzBkRg0Kb2tieHJrdkpvVHNjVTJiSDBxcnlLd0Rad2ZOa1RFNzI0ZmpWbjNlcHpTaGdJVEc2ZnUzZVhYaDVuOW9pZ3FKeQ0KaUVuNDNPNDh0dHBRZGdSaE9GZ0hnS3JLRkUveCtjKzdML2tZWnNQeU1UcjNQNXFsQVh6eFhUcGc4VjVIZlRZUA0KN2t5STRpWXlZTElnaEMxSDlSLzlZd1lGOVM5YlJZc1FnTE5oVnkwQ2dZQVdZTFFFd1ZQUXd3VkJGZlpkbklmcw0KRmNuVkRRcVRhT3psaVh3MGNYbGt4SzcwY0JxbUZHYjFEZTZPVGJVbCszVkoyTHpmdXZqNjJtZ1BqdmNmTE9CLw0KdWxjajRJRWNJcE5tejdHSmI3NytiS1B4anU4b0VNV1pkT2UyZGU0TEhuT1JRUDNScjdVdGpaZkFwdW9nNEJxZg0KcEc1U2lWZTVlaFpmcG9KajV0bC8vUUtCZ1FDelM0Mis4bkVnNkI0UDNnS0JHWGxUbjdsRE51KzY1NFlVaW9tZw0KSVRONU00VFJrWUFqRUZoYWVodHFMd25ObWxvT3dxWUt6MW01WXFMR0V3UGNRQ3RBZGFPZlhWVmRldUVMZ2ptSQ0KOGoyUFFDVEZLeE1wV3laMXF4bWpUek56azdKR1lVaERLUUlqUkl5eG1hcDQ2NHpVdjhrcVdicXBnTDlzVXNZZQ0KZnQ3cGFRS0JnR3YrUUVNL1RMY3pBRTRzUUNsNDNaeG04WCsyMjhoUnB5ajAwMkxhMnNlc3ZzR3ZKeEorelF6Yg0KQUN3S1RqOWtaSHRtNnVKYWNsUUVJeXJramYySDFFNWpUWGFRWjlCSHNnQVpqMWdPaDkwUnhPZEt4dTNHZVphOQ0KK3E4K0VlWnNSaXhyVTBtby8ySFIxSk1VZ1VaakE2azB2cVVpZ0U1RytZMUVwUHRkZUxpbg0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
  labels:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  template:
    metadata:
      labels:
        app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
      containers:
        - name: server
          image: ghcr.io/defenseunicorns/pepr/controller:v0.13.3
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - f8a0548747afb1817cef44ab024a6288215a918fd7cd3ee60c659b435e655e40
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          env:
            - name: PEPR_PRETTY_LOG
              value: 'false'
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: api-token
              mountPath: /app/api-token
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-tls
        - name: api-token
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-api-token
        - name: module
          secret:
            secretName: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  namespace: pepr-system
spec:
  selector:
    app: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b-module
  namespace: pepr-system
type: Opaque
data:
  module-f8a0548747afb1817cef44ab024a6288215a918fd7cd3ee60c659b435e655e40.js.gz: >-
    H4sIAAAAAAAAE41WbZPbNBD+3l+hCuZqg6wmkym0zviOTkqZQt+m19IZbsKcbG0SNY5kJPlCSP3fWclJSNsc8CGOLO1qd59nX3wjLKmLV+UHqDyXMFMaXlvTgPWb8Q2eySLRzKTFeY3/VIsVULa9EXULuWGV0TM1b60oa8jvDro0qiwKC3+0ykJCG2gs7XfLYhu0cwp/ilVTQ7aGcmHMkrIbsE4ZndMBH/AhZRJcZVXj4x5lS9isjZUuv+qvY3T50OGzMbWqNhnoOfoc3vEwWxnZ1uHNQdVa5Td0ynoJl2+1kWj/vBg+REMD2rGgkt/mVtsqmdOqfPDdoxHMMjkcVdmDGQyz8oGQWfXw+8FMPhoOy1FJmdE/WmtsTtVcG4v2Rb0WG/csvvUWXCMqdOJqympRQh1WXcf6SNE3uhzJzIFvG5qHNanq1nlAAqAGDyRGJ+GGnJ2R4+PKgjg+zrLlyGXCzsm9DDfKdv6DA4sQ54N7GLGEBrQEXakASIyf/o6oj/iIdl0kSpykryk0rIngE9GIUtWIbHIbcJ/w95g4FY7JToxUhwuIN8QtzJqE307bEeR6SdbKL8hvws4IorYUc0AYmtpsVqC945QdA0r/Qjk67VK2fb8Anbdd0YzbRHDBLwHh8Sl/5iYRJvnKvmtkWCS4qV/ub0n6O1L+Hu0+D/Rg7L3hrDecKT0zKPCi9aie6OJ8i7QQU2j+RqwZMMtccXc49naztYXwpkwMR0siPtJwOOgq4asFHh+ddEEBip8vX73kjbAOEpv2colPt35hEZoAfEyv5PqpUDXIAFwUJn4BxMUg/7kyJ19vfXeddjPUCE6imzMCF7yPBOTErBqjA5IXF1fT1HOHMbWuKAr6JIooPadnZ4jgczPnIfDk+i0aqvZ6wQAPFHREOYJ1ZnGz3uw4Qu3rlAE/iL/fUXvBr/xF1Jviknpw/pA0uGPKmKjyJ9BgRcge9Aj4/PB60TsUk/p2jxbCEVEj3XKDa0nEPrUwA7EnIPcEgSHKc/LS+N0m+kyENgin5ddpnpzw/uPHU7vFtjsZ61XvzrTYfhrnvtt8ssl6AnL6ptU6gM++xCI/RgIbxxLzawVeRNrDnay3mKbpOFB5d3BxlGZF6Y1IYpY5b9GEmm0SlM2PZb44xn4u3EZXZNbqKtglyzgMtmItlCfzZDhIxyHDYNccsDHzX9oSJnEujIHXRsin1qyewEy0tU96cYu0rsQSHjdqUitELelVJ9gsfx3ibhrrKOZukfTGLA+UHipW9qUdZlJfuikvjdywVV97/rj21HF5rVJWFeoEYeZEUo6rW9JSHZGBlVLtS4hetlUFIEFSdtrI5yaKKmX+P4hSacr2KDShN9wKA/PsxihJBv/6t10glDh0ceogUx4dzN5uGsDBI5oGh2oM6z7ax1Y3V1W2AouNMFr+9oMzGifFvkm5dIv2W6tJX5zQ96l3OnwShD7Vxn4bG9W+lfcNK7Spz+J0KbYt5rpOJkuc4DVA81jLyULoOVxGgHEYHXJxnuiD8ZB++NmyUsiwKc5xjr5VKzCtTwzT3wxhlKZ46Xx3Kd4SFBb8Nc63F/GLISnZVTNNx3fu3/+KONPaCl4gGOjYuzfPizhd/8+XAP/gMLObO38DI0EF91YJAAA=
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
webhooks:
  - name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b.pepr.dev
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDdERDQ0FaeWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBY01Sb3dHQVlEVlFRREV4RlFaWEJ5DQpJRVZ3YUdWdFpYSmhiQ0JEUVRBZUZ3MHlNekE1TWpBeE56VXpNemRhRncweU5EQTVNakF4TnpVek16ZGFNQUF3DQpnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDY09PNmg2NjZrYWtGbUJaaDROSitSDQprQzFxUFJHR01PWVVsWVFmS0FJSGpSSFZleU9PQUNkcWVqVUd2VzRkTHE1dVQ4QVh3ZXFIekwzQ1M5ejZQNVlCDQplZG5oQU1RZDFsMVphRWdmU0ZnaFlxNlFweGlxc1o4alZtVFFBOExlNWRYcDdERGs4RVNrQ0xKOGU2SEM4SmxQDQo5SUdNMisvZjZrMjdTWGFCYUJzL0swLzZ4SFk0ZEFOODJnL1crTnBhWFdUYk5QWmpMVFdPM1BPc1BrRFNydFp5DQpVeFUyM3ZDRFp4elBIRU1IVE0vc1oyOXRnSldDUU5OaFhHWTEvaWdGVWFZeGhadzZDL2g3ZHlTbzF6bm51a2QwDQpvMHlUWlAvM0Jod2lvZDRSdnlSNDY0aGhpeFRSYVFsNFBrU0dWakVIbXA5WURZNm9YUzZpdERYU3JyZmNOY01UDQpBZ01CQUFHakhUQWJNQXdHQTFVZEV3UUZNQU1CQWY4d0N3WURWUjBQQkFRREFnTDBNQTBHQ1NxR1NJYjNEUUVCDQpDd1VBQTRJQkFRQ1lEV3RDaUZRNnA5UjV5UHM0YjRnNTJHb2Via3RyVDh5QzQ5VEZ5aVRMeVVvSUM4WXhscy9WDQpGWnlMdW5FZjd2czhIcVNqTUIrNzMxamFlYmZZclQ4ZzZxUitQNmFyU1l3eTBDNHdoek5zOG5IQTlGZXR2V1VuDQpVbWdvRTNQc2c5eDhPWFpsQ21DNHRFWElIRGovbkhxbUswYXE1SkdUZFRCM01yOG5PWVpLWGdSSkswY0ZHMkdoDQpITFB3ZCttZkFudTh5U3JxejRNeE1URVE5RVZTckpHVE1CRDA3NnFncTlTK090cUh6VFpmcGpkdytrMTJFQkFMDQpUZEVFTmdKeFZnQjFrMnArMm1KcU5WbEZITzZ0c3hCcG9TU1o4L0NFV1VrdkJBdTh2dkpSajRRMFFjSG45RjcvDQoreVl3Tzd1K0FNVWo5L2pCWWVvdVRUQllPNEkwVmU4bQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
      service:
        name: pepr-cb5693ef-d13c-5fe1-b5ad-c870fd911b3b
        namespace: pepr-system
        path: >-
          /mutate/317035b46b93658344cc56093109e104f32ec03c442d864ec82297f6a01e9d12
    failurePolicy: Ignore
    matchPolicy: Equivalent
    timeoutSeconds: 10
    namespaceSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    objectSelector:
      matchExpressions:
        - key: pepr.dev
          operator: NotIn
          values:
            - ignore
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - pepr-system
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
    sideEffects: None
