grafana:
  enabled: true
  adminUser: "zarf-admin"
  adminPassword: "###ZARF_LOGGING_AUTH###"
  # K8s 1.25+ compatibility until loki stack upgrades the grafana chart to 6.36.1
  rbac:
    pspEnabled: false
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/monitor"
      serve_from_sub_path: true
promtail:
  extraScrapeConfigs:
    - job_name: journal
      journal:
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ["__journal__systemd_unit"]
          target_label: "unit"
        - source_labels: ["__journal__hostname"]
          target_label: "hostname"

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
