apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: nginx
  labels:
    app: nginx
data:
  01_http.conf: |
    add_header X-Kubernetes-Pod $hostname;
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to ###JACKAL_VAR_SITE_NAME###!</title>
        <style>
          ###JACKAL_VAR_STYLE###
        </style>
      </head>
      <body>
        <!-- Test two separate variables on the same line -->
        <h1>Welcome to the ###JACKAL_VAR_SITE_NAME###!</h1><h2>Brought to you by ###JACKAL_VAR_ORGANIZATION###.</h2>
        <p>Below is a Terraform File templated by Jackal</p>
        <pre>
          ###JACKAL_VAR_MODIFIED_TERRAFORM###
        </pre>
        <pre>File SHASUM: ###JACKAL_VAR_MODIFIED_TERRAFORM_SHASUM###</pre>
        ###JACKAL_VAR_OPTIONAL_FOOTER###
      </body>
    </html>
