apiVersion: v1
kind: Service
metadata:
  name: nginx-connect
  namespace: nginx
  annotations:
    jackal.dev/connect-description: "Launch the nginx static site."
  labels:
    jackal.dev/connect-name: nginx
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
