---
apiVersion: v1
kind: Service
metadata:
  name: doom
  annotations:
    jackal.dev/connect-description: "Play doom!!!"
    jackal.dev/connect-url: "?doom"
  labels:
    # Enables "jackal connect doom"
    jackal.dev/connect-name: doom
spec:
  selector:
    app: game
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: game
  annotations:
    jackal.dev/connect-description: "Play some old dos games 🦄"
  labels:
    # Enables "jackal connect games"
    jackal.dev/connect-name: games
spec:
  selector:
    app: game
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
