name: Zarf Injector Rust Binaries

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Version tag"
        required: true
      branchName:
        description: "Branch to build the injector from"
        required: true

jobs:
  build-injector:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: "Build Rust Binary for x86_64 and arm64"
        run: |
          make build-injector-linux
          cd src/injector/target
          mkdir -p ../dist
          cp x86_64-unknown-linux-musl/release/zarf-injector ../dist/zarf-injector-amd64
          cp aarch64-unknown-linux-musl/release/zarf-injector ../dist/zarf-injector-arm64
          cd ../dist
          shasum zarf-injector-amd64 >> checksums.txt
          shasum zarf-injector-arm64 >> checksums.txt

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_GOV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GOV_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Sync Artifacts to S3
        run: |
          aws s3 sync src/injector/dist/ s3://zarf-public/injector/${{ github.event.inputs.versionTag }}/
