name: Test ECR Publishing
on:
  schedule:
   - cron: '0 7 * * * ' ## Every day at 0700 UTC

  workflow_dispatch: ## Give us the ability to run this manually


# Abort prior jobs in the same workflow / PR
concurrency:
  group: ecr-publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build the Zarf binary
        run: make build-cli-linux-amd

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5727f247b64f324ec403ac56ae05e220fd02b65f # v2.1.0
        with:
          role-to-assume: ${{ secrets.AWS_NIGHTLY_ROLE }}
          aws-region: us-east-1

      # NOTE: The aws cli will need to be explicitly installed on self-hosted runners
      - name: Login to the ECR Registry
        run: aws ecr-public get-login-password --region us-east-1 | ./build/zarf tools registry login --username AWS --password-stdin public.ecr.aws

      - name: Test publishing and pulling to ECR
        run: go test ./src/test/nightly/ecr_publish_test.go

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
