name: Zarf Application Package Publishing

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Branch to build the packages from"
        required: true
        default: "main"

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Install The Latest Release Version of Zarf
        uses: defenseunicorns/setup-zarf@main

      - name: "Login to GHCR"
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Build And Publish Application Packages
        # Create the dos-games package with the cosign signature, publish to ghcr and copy the tags to allow 'uname -m' to work
        run: |
          zarf package create -o build -a amd64 examples/dos-games --key=awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} --confirm
          zarf package create -o build -a arm64 examples/dos-games --key=awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} --confirm

          zarf package publish ./build/zarf-package-dos-games-amd64-1.0.0.tar.zst oci://ghcr.io/defenseunicorns/packages
          zarf package publish ./build/zarf-package-dos-games-arm64-1.0.0.tar.zst oci://ghcr.io/defenseunicorns/packages

          zarf tools registry copy ghcr.io/defenseunicorns/packages/dos-games:1.0.0-amd64 ghcr.io/defenseunicorns/packages/dos-games:1.0.0-x86_64
          zarf tools registry copy ghcr.io/defenseunicorns/packages/dos-games:1.0.0-arm64 ghcr.io/defenseunicorns/packages/dos-games:1.0.0-aarch64
        env:
          AWS_REGION: ${{ secrets.COSIGN_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COSIGN_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COSIGN_AWS_ACCESS_KEY }}
