name: Jackal Application Package Publishing

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Branch to build the packages from"
        required: true
        default: "main"

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Build Jackal binary
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          build-examples: "false"

      - name: "Login to GHCR"
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Build And Publish Application Packages
        # Create the dos-games package with the cosign signature, publish to ghcr and copy the tags to allow 'uname -m' to work
        run: |
          build/jackal package create -o build -a amd64 examples/dos-games --confirm
          build/jackal package create -o build -a arm64 examples/dos-games --confirm

          # Publish a the signed dos-games package
          build/jackal package publish ./build/jackal-package-dos-games-amd64-1.0.0.tar.zst oci://ghcr.io/racer159/packages
          build/jackal package publish ./build/jackal-package-dos-games-arm64-1.0.0.tar.zst oci://ghcr.io/racer159/packages

          # Publish a skeleton of the dos-games package
          build/jackal package publish examples/dos-games oci://ghcr.io/racer159/packages
