name: Analyze CVEs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "src/ui/package.json"
      - "src/ui/package-lock.json"
      - "cargo.toml"
      - "cargo.lock"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Check for CVEs in Dependencies
        run: "make test-cves"
