name: Docs Skip Shim
on:
  pull_request:
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

# This is here to act as a shim for branch protection rules to work correctly.
# This is ugly but this seems to be the best way to do this since:
#  - Job names in a workflow must be unique
#  - When paths are ignored not all jobs are reported to the branch protection rules
#  - Multiple jobs of the same name are still required by branch protection rules

# For more info see below:
# https://github.com/orgs/community/discussions/54877
# https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-skip-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: |
          echo skipped

  validate-k3d:
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: |
          echo skipped

  validate-k3s:
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: |
          echo skipped

  validate-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: |
          echo skipped

  validate-minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Skipped
        run: |
          echo skipped
