name: Test Windows Binary
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Optimize caching
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        shell: cmd

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Run Windows unit tests
        run: make test-unit
        shell: pwsh

      - name: Build Windows binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          os: windows
          shell: pwsh

      # TODO: (@WSTARR) Builds an init package manually off of the v0.30.1
      # release since Windows in GitHub cannot natively build linux containers
      # and the tests this workflow run do not use the agent at all!
      - name: Build init-package
        run: |
          make release-init-package ARCH=amd64 AGENT_IMAGE_TAG=v0.30.1

      - name: Run windows E2E tests
        run: make test-e2e ARCH=amd64 -e SKIP_K8S=true
        shell: pwsh
