name: Test Upgrade
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-upgrade-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Build PR binary and zarf init package
        uses: ./.github/actions/packages
        with:
          build-examples: "false"

      # Upload the contents of the build directory for later stages to use
      - name: Upload build artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: build-artifacts
          path: build/
          retention-days: 1

  validate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Download build artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: build-artifacts
          path: build/

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Make Zarf executable
        run: |
          chmod +x build/zarf

      - name: Install release version of Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          download-init-package: true

      - name: Initialize the cluster with the release version
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of zarf installed
        #       in a previous step. This test run will the current release to create a K3s cluster.
        run: |
          sudo env "PATH=$PATH" CI=true zarf init --components k3s,git-server,logging --set REGISTRY_NODEPORT=31337 --confirm

      # Before we run the regular tests we need to aggressively cleanup files to reduce disk pressure
      - name: Cleanup files
        uses: ./.github/actions/cleanup-files

      - name: Create and deploy the upgrade test packages
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of zarf installed
        #       in a previous step. This test run will the current release to create a K3s cluster.
        run: |
          zarf package create src/test/upgrade --set PODINFO_VERSION=6.3.3 --confirm
          sudo env "PATH=$PATH" CI=true zarf package deploy zarf-package-test-upgrade-package-amd64-6.3.3.tar.zst --confirm
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe deployments -n=podinfo-upgrade
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe pods -n=podinfo-upgrade

      - name: Run tests
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of go installed
        #       in a previous step. This test run will use this PR's Zarf to create a K3s cluster.
        run: |
          sudo env "PATH=$PATH" CI=true APPLIANCE_MODE=true APPLIANCE_MODE_KEEP=true make test-e2e-with-cluster ARCH=amd64

      - name: "Describe nodes, pods and deployments"
        # NOTE: We describe nodes, pods and deployments here to help understand failures
        run: |
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe nodes
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe deployments -n=podinfo-upgrade
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe pods -n=podinfo-upgrade

      # Before we run the upgrade tests we need to aggressively cleanup files to reduce disk pressure
      - name: Cleanup files
        uses: ./.github/actions/cleanup-files

      - name: Run the upgrade tests
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of zarf installed
        #       in a previous step. This test run will the current release to create a K3s cluster.
        run: |
          sudo env "PATH=$PATH" CI=true zarf tools kubectl describe nodes

          zarf package create src/test/upgrade --set PODINFO_VERSION=6.3.4 --confirm

          sudo env "PATH=$PATH" CI=true make test-upgrade ARCH=amd64

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
