name: Test External Git & Registry
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-external-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          build-examples: "false"

      - name: Setup k3d
        uses: ./.github/actions/k3d

      - name: Run external service test
        run: make test-external

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
