name: Test Windows Binary
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "package.json"
      - "package-lock.json"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Optimize caching
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        shell: cmd

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build windows binary
        run: make build-cli-windows-amd
        shell: pwsh

      # Builds an init package manually off of the v0.23.6 release since
      # Windows in GitHub cannot natively build linux containers and
      # the tests this workflow runs do not use the agent at all!
      - name: Build init-package
        run: |
          make release-init-package ARCH=amd64 AGENT_IMAGE_TAG=v0.25.2

      - name: Build zarf packages
        run: make build-examples ARCH=amd64
        shell: pwsh

      - name: Run windows tests
        run: make test-e2e ARCH=amd64 -e SKIP_K8S=true
        shell: pwsh
