name: Test K3s Cluster
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "package.json"
      - "package-lock.json"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-k3s-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages

      - name: "Run Tests"
        # NOTE: "PATH=$PATH" preserves the default user $PATH. This is needed to maintain the version of go installed
        #       in a previous step. This test run will use Zarf to create a K3s cluster, and a brand new cluster will be
        #       used for each test
        # chown the logs since they were orignally created as root
        run: |
          sudo env "PATH=$PATH" CI=true APPLIANCE_MODE=true make test-e2e ARCH=amd64

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
