apiVersion: v1
kind: Service
metadata:
  name: zarf-connect-git
  labels:
    # Enables "zarf connect git"
    zarf.dev/connect-name: git
  annotations:
    zarf.dev/connect-description: "Internal Zarf Git Server (Gitea)"
spec:
  ports:
  - port: 3000
