persistence:
  storageClass: "###JACKAL_STORAGE_CLASS###"
  claimName: "###JACKAL_VAR_GIT_SERVER_EXISTING_PVC###"
  size: "###JACKAL_VAR_GIT_SERVER_PVC_SIZE###"
  accessModes:
    - "###JACKAL_VAR_GIT_SERVER_PVC_ACCESS_MODE###"
  create: ###JACKAL_VAR_GIT_SERVER_CREATE_PVC###

replicaCount: ###JACKAL_VAR_GIT_SERVER_REPLICA_COUNT###

gitea:
  admin:
    username: "###JACKAL_GIT_PUSH###"
    password: "###JACKAL_GIT_AUTH_PUSH###"
    email: "jackal@localhost"
  config:
    APP_NAME: "Jackal Gitops Service"
    server:
      DISABLE_SSH: true
      OFFLINE_MODE: true
      ROOT_URL: http://jackal-gitea-http.jackal.svc.cluster.local:3000
    database:
      DB_TYPE: sqlite3
      # Note that the init script checks to see if the IP & port of the database service is accessible, so make sure you set those to something that resolves as successful (since sqlite uses files on disk setting the port & ip won't affect the running of gitea).
      HOST: jackal-docker-registry.jackal.svc.cluster.local:5000
    security:
      INSTALL_LOCK: true
    service:
      DISABLE_REGISTRATION: ###JACKAL_VAR_GIT_SERVER_DISABLE_REGISTRATION###
    repository:
      ENABLE_PUSH_CREATE_USER: true
      FORCE_PRIVATE: true
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
resources:
  requests:
    cpu: "###JACKAL_VAR_GIT_SERVER_CPU_REQ###"
    memory: "###JACKAL_VAR_GIT_SERVER_MEM_REQ###"
  limits:
    cpu: "###JACKAL_VAR_GIT_SERVER_CPU_LIMIT###"
    memory: "###JACKAL_VAR_GIT_SERVER_MEM_LIMIT###"

image:
  fullOverride: "###JACKAL_CONST_GITEA_IMAGE###"
  rootless: true

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false

strategy:
  type: "Recreate"
